services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey # Change this in production
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

volumes:
  meili_data:
